// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Taggly.UrlShortener.Infrastructure.Persistence;

#nullable disable

namespace Taggly.UrlShortener.Infrastructure.Migrations
{
    [DbContext(typeof(UrlShortenerDbContext))]
    [Migration("20251015153619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Taggly.UrlShortener.Domain.Entities.ShortUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOnUtc");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<DateTime?>("ExpirationDate")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExpirationDate");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedOnUtc");

                    b.HasKey("Id")
                        .HasName("pk_short_urls");

                    b.ToTable("ShortUrls", (string)null);
                });

            modelBuilder.Entity("Taggly.UrlShortener.Domain.Entities.ShortUrl", b =>
                {
                    b.OwnsOne("Taggly.UrlShortener.Domain.ValueObjects.OriginalUrl", "OriginalUrl", b1 =>
                        {
                            b1.Property<Guid>("ShortUrlId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("character varying(2048)")
                                .HasColumnName("OriginalUrl");

                            b1.HasKey("ShortUrlId");

                            b1.ToTable("ShortUrls");

                            b1.WithOwner()
                                .HasForeignKey("ShortUrlId")
                                .HasConstraintName("fk_short_urls_short_urls_id");
                        });

                    b.OwnsOne("Taggly.UrlShortener.Domain.ValueObjects.ShortCode", "ShortCode", b1 =>
                        {
                            b1.Property<Guid>("ShortUrlId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("ShortCode");

                            b1.HasKey("ShortUrlId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_short_urls_short_code");

                            b1.ToTable("ShortUrls");

                            b1.WithOwner()
                                .HasForeignKey("ShortUrlId")
                                .HasConstraintName("fk_short_urls_short_urls_id");
                        });

                    b.OwnsOne("Taggly.UrlShortener.Domain.ValueObjects.UrlMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ShortUrlId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("CreatedBy")
                                .HasMaxLength(100)
                                .HasColumnType("uuid")
                                .HasColumnName("CreatedBy");

                            b1.Property<string>("Description")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Description");

                            b1.Property<DateTime?>("ExpirationDate")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ExpirationDate");

                            b1.HasKey("ShortUrlId");

                            b1.ToTable("ShortUrls");

                            b1.WithOwner()
                                .HasForeignKey("ShortUrlId")
                                .HasConstraintName("fk_short_urls_short_urls_id");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("OriginalUrl")
                        .IsRequired();

                    b.Navigation("ShortCode")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
